name = "n-library-guestbook"
main = "src/index.js"
compatibility_date = "2026-08-18"
account_id = "6e4526f8a97c1a34d4f4101cf493e291"

[[d1_databases]]
binding = "DB"
database_name = "n-library-guestbook"
database_id = "REPLACE_WITH_DATABASE_ID"
